services:
  daily_gym_api:
    build: .
    ports:
      - "3000:3000"
    network_mode: "host"
    volumes:
      - ".:/rails"
      - gym_app_api_gems:/usr/local/bundle
    depends_on:
      - db
    environment:
      DATABSE_USER: "postgres"
      DATABSE_PASSWORD: "password"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  gym_app_api_gems:
